/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "ADC_In.h"
#include "ADC_In_aliases.h"
#include "CEPIN.h"
#include "CEPIN_aliases.h"
#include "GREEN.h"
#include "GREEN_aliases.h"
#include "BLUE.h"
#include "BLUE_aliases.h"
#include "RED.h"
#include "RED_aliases.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "BLE_1_gatt.h"
#include "BLE_1.h"
#include "BLE_1_hids.h"
#include "BLE_1_bas.h"
#include "BLE_1_HAL_PVT.h"
#include "BLE_1_STACK_PVT.h"
#include "BLE_1_StackGap.h"
#include "BLE_1_StackGatt.h"
#include "BLE_1_StackGattDb.h"
#include "BLE_1_StackHostMain.h"
#include "BLE_1_StackL2cap.h"
#include "BLE_1_scps.h"
#include "BLE_1_dis.h"
#include "BLE_1_StackGattServer.h"
#include "BLE_1_StackGattClient.h"
#include "BLE_1_Stack.h"
#include "BLE_1_eventHandler.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "BLE_1_bless_isr.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

